import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'app_language.dart';
import 'number_formatter.dart';

/// The core localization class providing key-based translation lookup,
/// argument interpolation, and strict English digit enforcement.
class AppLocalizations {
  final Locale locale;
  Map<String, String> _localizedStrings = {};

  AppLocalizations(this.locale) {
    _loadBuiltInStrings();
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  /// Retrieve the [AppLocalizations] instance from the widget tree.
  static AppLocalizations of(BuildContext context) {
    final instance = Localizations.of<AppLocalizations>(context, AppLocalizations);
    return instance ?? AppLocalizations(const Locale('en'));
  }

  /// Built-in fallback dictionary for English strings.
  static const Map<String, String> _enStrings = {
    'accept_offer_btn': 'Accept Offer',
    'actions_tools': 'Actions & Tools',
    'active_demand_badge': 'Active Demand',
    'active_demands_badge': '{count} Active',
    'active_inventory': 'Active Inventory',
    'active_lot_badge': 'Active Lot',
    'active_lots_summary': '2 Active Lots • 180 qtl',
    'active_market': 'Active Market',
    'active_past_purchases': 'Active & Past Purchases',
    'aggregation_hero_desc': 'Combine produce with verified farmers nearby to create larger trade lots, attract tier-1 bulk buyers, and negotiate stronger mandi rates.',
    'ai_market_signal': 'AI Market Signal',
    'ai_recommendation_wheat': 'Lock profits for 40% stock today. Remaining lot can gain from expected surge next week.',
    'app_name': 'KisanSetu',
    'app_tagline': 'Direct Agricultural Marketplace',
    'asking_price': 'Asking Price',
    'asking_price_format': 'Asking: {price}',
    'asking_rate': 'Asking Rate',
    'available_from_label': 'Available From: 03 Sep 2026',
    'available_lots': 'Available Lots',
    'available_quantity': 'Available Quantity',
    'available_vehicles': 'Available Vehicles',
    'available_volume': 'Available Volume',
    'available_volume_quintals': 'Available Volume (Quintals)',
    'back_to_dashboard_btn': 'Back to Dashboard',
    'badge_produce_lot': 'Produce Lot',
    'badge_ready_to_submit': 'Ready to Submit',
    'based_on_live_trend': 'Based on live price trend ({trend}%) and demand level ({demand}).',
    'based_on_price_movement': 'Based on current price movement and buyer demand',
    'best_fit_badge': 'Best Fit',
    'best_scenario_prefix': 'Best Scenario: {scenario}',
    'broadcast_demand_btn': 'Broadcast Demand',
    'broadcast_demand_desc': 'Broadcast your required quantity, target price & delivery location',
    'browse_farmer_produce_lots': 'Browse Farmer Produce Lots',
    'browse_lots': 'Browse Lots',
    'browse_lots_title': 'Browse Lots',
    'browse_lots_to_bid_desc': 'Browse available lots to make bids and negotiate with farmers.',
    'bulk_advantage_desc': 'Larger lots can attract bulk buyers and improve bargaining power.',
    'bulk_selling_advantage': 'Bulk Selling Advantage',
    'buyer_demand_board_desc': 'View active commodity requirements posted by buyers',
    'buyer_demand_board_title': 'Buyer Demand Board',
    'buyer_demand_label': 'Buyer Demand',
    'buyer_demand_overview': 'Buyer Demand Overview',
    'buyer_offers_title': 'Buyer Offers',
    'combined_lot_label': 'Combined Lot',
    'commodity_crop': 'Commodity Crop',
    'common_back': 'Back',
    'common_retry': 'Retry',
    'compare_net_price': 'Compare Net Price',
    'compare_sell_hold_desc': 'Compare Sell Now vs Hold scenarios with storage and transport costs.',
    'compatibility_score': 'Compatibility Score: {score}%',
    'confirm_and_list_produce': 'Confirm & List Produce Lot',
    'confirm_and_submit_offer': 'Confirm & Submit Offer',
    'confirm_deal_btn': 'Confirm Deal',
    'continue_to_make_offer': 'Continue to Make Offer',
    'costs_breakdown_text': '• Transport: ₹2,500 flat per haulage\n• Storage (Hold 7d): ₹100/quintal\n• Storage (Hold 15d): ₹200/quintal',
    'create_aggregated_lot_btn': 'Create Aggregated Lot',
    'create_new_lot': 'Create New Lot',
    'create_new_lot_desc': 'List your crop and connect with buyers',
    'crop_all': 'All',
    'crop_basmati_rice': 'Basmati Rice',
    'crop_chana': 'Chana (Gram)',
    'crop_maize': 'Maize',
    'crop_market_rate': '{crop} Market Rate',
    'crop_mustard': 'Mustard',
    'crop_pooling': 'Crop Pooling',
    'crop_rice': 'Rice',
    'crop_soybean': 'Soybean',
    'crop_wheat': 'Wheat',
    'current_market_recommendation': 'Current Market Recommendation',
    'data_shown_based_on_records': 'Data shown is based on the latest market records available in KisanSetu.',
    'deal_number_header': 'Deal #{number} • {crop} ({qty})',
    'deal_specifications': 'Deal Specifications',
    'deal_summary': 'Deal Summary',
    'decline_offer_btn': 'Decline',
    'delhi_ncr_distance': 'Delhi NCR • 65 km away',
    'delivery_location_depot': 'Delivery Location / Depot',
    'delivery_progress': 'Delivery Progress',
    'delivery_timeline': 'Delivery Timeline',
    'direct_bids_realization_desc': 'Direct aggregate bids currently yield ₹120-150/qtl higher realization.',
    'direct_farmer_opportunities': 'Direct Farmer Opportunities',
    'direct_procurement_savings_desc': 'Direct procurement saves up to 8% on intermediary Mandi handling and commission charges.',
    'direct_purchase_reqs_desc': 'Direct purchase requirements posted by institutional buyers will appear here.',
    'dispatch_route': 'Dispatch Route',
    'dispatch_status_updated': 'Dispatch status updated to {status}',
    'dispatches_deals_desc': 'Track accepted deals, pickups & direct payments',
    'dispatches_deals_title': 'Dispatches & Deals',
    'distance_away': '{distance} km away',
    'enter_quantity_in_qtl': 'Enter quantity in quintals',
    'err_cannot_exceed_qty': 'Cannot exceed available lot quantity ({qty})',
    'err_enter_asking_rate': 'Enter asking rate',
    'err_enter_delivery_location': 'Enter delivery location',
    'err_enter_qty': 'Enter quantity',
    'err_enter_target_price': 'Enter target price',
    'err_enter_warehouse_loc': 'Enter farm/warehouse location',
    'err_incomplete_offer_details': 'Incomplete offer details. Cannot proceed with acceptance.',
    'err_invalid_price_or_qty': 'Invalid offer price or quantity.',
    'err_must_be_gt_0': 'Must be greater than 0',
    'err_offer_not_found': 'Offer details could not be found.',
    'err_offer_price_req': 'Offer price is required',
    'err_qty_req': 'Quantity is required',
    'err_valid_price': 'Enter a valid price greater than 0',
    'err_valid_qty': 'Enter a valid quantity greater than 0',
    'escrow_details': 'Escrow Details',
    'estimated_contract_total': 'Estimated Contract Total',
    'estimated_net_realisable_price': 'Estimated Net Realisable Price',
    'estimated_prototype_costs': 'Estimated Prototype Costs',
    'estimated_total_value': 'Estimated Total Value',
    'expected_within_24h': 'Expected within 24 hours after delivery verification',
    'failed_accept_offer': 'Failed to accept offer: {error}',
    'failed_create_lot': 'Failed to create lot: {error}',
    'failed_decline_offer': 'Failed to decline offer. Please try again.',
    'failed_load_active_lots': 'Failed to load active lots. Please try again.',
    'failed_load_offers': 'Failed to load your offers. Please try again.',
    'failed_update_status': 'Failed to update status: {error}',
    'farm_warehouse_depot': 'Farm Warehouse / Village Depot',
    'farmer_asking_price': 'Farmer Asking Price',
    'farmer_asking_rate': 'Farmer Asking Rate (₹/Quintal)',
    'final_payable_amount': 'Final Payable Amount',
    'fulfillment_timeline': 'Fulfillment Timeline',
    'good_quality': 'Good Quality',
    'greeting_afternoon': 'Good afternoon,',
    'greeting_evening': 'Good evening,',
    'greeting_morning': 'Good morning,',
    'harvest_lot_volume_qtl': 'Harvest Lot Volume (Quintals)',
    'harvested_lot_details': 'Harvested Lot Details',
    'harvested_produce_lots': 'Harvested Produce Lots',
    'hint_delivery_location': 'e.g., Meerut Depot, Partapur',
    'hint_farm_warehouse': 'e.g., Farm Warehouse, Daurala',
    'intelligent_matching': 'Intelligent Buyer Matching',
    'intelligent_matching_desc': 'Compare net realisable rates across institutional buyers',
    'intelligent_matching_title': 'Intelligent Buyer Matching',
    'lang_en': 'English',
    'lang_hi': 'हिन्दी',
    'language': 'Language',
    'list_produce_lot_title': 'List Produce Lot',
    'listed_lots_count': '{count} Listed Lots',
    'listings_count': '{count} listings',
    'live_apmc': 'Live APMC',
    'live_data_badge': 'Live Data',
    'logistics_fulfillment_title': 'Logistics & Fulfillment',
    'logistics_label': 'Logistics',
    'logistics_tracking_desc': 'Logistics tracking and dispatch arrangement will appear once an offer is accepted.',
    'lot_details_title': 'Lot Details',
    'lot_distance': 'Distance',
    'lot_id_format': 'Lot ID: {id}',
    'lot_id_label': 'Lot ID',
    'lot_id_prefix': 'Lot ID: {id}',
    'lot_location': 'Location',
    'lot_quality': 'Quality',
    'lot_quantity': 'Quantity',
    'make_an_offer': 'Make an Offer',
    'make_offer_title': 'Make an Offer',
    'make_offer_view_lot': 'Make Offer / View Lot',
    'manage_produce_batches': 'Manage Produce Batches',
    'mandi_comparison': 'Mandi Comparison',
    'mandi_location_label': 'Mandi / Location',
    'mandi_rate_meerut': 'Meerut Mandi Rate',
    'market_advisory_title': 'Market Advisory',
    'market_assumptions': 'Market Assumptions',
    'market_intelligence_title': 'Market Intelligence',
    'market_overview': 'Market Overview',
    'market_recommendation': 'Market Recommendation',
    'market_recommendation_desc': 'Get HOLD / SELL guidance based on live mandi conditions',
    'market_recommendation_title': 'Market Recommendation',
    'max_available_helper': 'Max available: {qty}',
    'model_net_returns_desc': 'Model net returns for selling now vs. holding with storage and freight deductions.',
    'msg_aggregated_lot_success': 'Aggregated lot created successfully',
    'msg_demand_broadcasted': 'Purchase demand broadcasted successfully!',
    'msg_failed_post_demand': 'Failed to post demand: {error}',
    'my_active_lots_desc': 'View listed crops, active lots & manage offers',
    'my_active_lots_title': 'My Active Lots',
    'my_lots': 'My Lots',
    'my_lots_desc': 'View and manage your listed crops',
    'my_offers': 'My Offers',
    'my_produce_lots_title': 'My Produce Lots',
    'my_purchases': 'My Purchases',
    'my_purchases_title': 'My Purchases',
    'my_submitted_offers': 'My Submitted Offers',
    'my_submitted_offers_desc': 'Track pending bids, accepted deals & farmer counter-proposals',
    'my_submitted_offers_title': 'My Submitted Offers',
    'nearby_farmers': 'Nearby Farmers',
    'need_active_lot_desc': 'You need an active lot of {crop} with available quantity to respond to this buyer demand.',
    'net_price': 'Net Price',
    'net_rate_2490': '₹2,490/qtl net',
    'net_rate_2520': '₹2,520/qtl net',
    'net_realisable_breakdown': 'Net Realisable Price Breakdown',
    'net_realisable_value': 'Net Realisable Value',
    'no_active_buyer_demands': 'No active buyer demands',
    'no_active_buyer_demands_found': 'No active buyer demands found.',
    'no_active_farmer_lots': 'No active farmer lots listed currently.',
    'no_active_lots': 'No active lots available',
    'no_buyer_offers_yet': 'No buyer offers received yet',
    'no_confirmed_deals': 'No confirmed deals found',
    'no_data_available_crop_market': 'No data is currently available for {crop} at {market}.',
    'no_market_data_wheat': 'No market data found for Wheat',
    'no_matching_active_lots': 'No matching active lots found',
    'no_offers_submitted_yet': 'No offers submitted yet',
    'no_produce_lots_found': 'No Produce Lots Found',
    'no_recorded_rates_found': 'No recorded rates found',
    'no_transactions_found': 'No Transactions Found',
    'noida_hub_distance': 'Noida Hub • 48 km away',
    'notif_buyer_offer_desc': 'Kisan Agro Flour Mills offered ₹2,470/qtl for your Wheat lot.\n10 min ago',
    'notif_buyer_offer_title': 'New Buyer Offer',
    'notif_logistics_desc': 'Transport has been arranged for your Wheat shipment.\nYesterday',
    'notif_logistics_title': 'Logistics Update',
    'notif_market_alert_desc': 'Wheat prices increased by 3.4% today in Meerut.\n1 hour ago',
    'notif_market_alert_title': 'Market Alert',
    'notif_offer_update_desc': 'Your offer for Wheat 150 qtl was accepted.\n3 hours ago',
    'notif_offer_update_title': 'Offer Update',
    'notifications_title': 'Notifications',
    'offer_accepted_success': 'Offer accepted successfully! Deal contract created.',
    'offer_declined_msg': 'Offer declined',
    'offer_details_title': 'Offer Details',
    'offer_progress': 'Offer Progress',
    'offer_submitted_desc': 'Your bid has been directly delivered to the farmer. You will be notified once they respond.',
    'offer_submitted_title': 'Offer Submitted!',
    'offer_summary': 'Offer Summary',
    'offer_terms': 'Offer Terms',
    'offered_price_label': 'Offered Price (₹/qtl)',
    'offered_quantity_label': 'Offered Quantity (qtl)',
    'offered_unit_price': 'Offered Unit Price',
    'offered_volume': 'Offered Volume',
    'offers_appear_here_desc': 'Offers submitted by prospective buyers will appear here.',
    'offers_count_badge': '{count} Offers',
    'orders_count': '{count} orders',
    'payment_auto_update_desc': 'Payment status will automatically update once the buyer completes bank settlement. The amount will be credited directly to your registered bank account.',
    'payment_breakdown': 'Payment Breakdown',
    'payment_details_title': 'Payment Details',
    'payment_timeline': 'Payment Timeline',
    'per_quintal_benchmark_wheat': '/ quintal benchmark (Wheat)',
    'per_quintal_wheat': '/ quintal (Wheat)',
    'post_commodity_demand_title': 'Post Commodity Demand',
    'post_crops_broadcast_desc': 'Post your harvested crops to broadcast available volume and receive buyer offers.',
    'post_demand': 'Post Demand',
    'post_demand_title': 'Post Commodity Demand',
    'post_new_lot_btn': 'Post New Lot',
    'post_new_produce_lot_desc': 'List harvested crop with quality, quantity & asking price',
    'post_new_produce_lot_title': 'Post New Produce Lot',
    'post_produce_lot_btn': 'Post Produce Lot',
    'premium_quality': 'Premium Quality',
    'price_per_qtl': '₹{price}/qtl',
    'price_realisation_simulator': 'Price Realisation Simulator',
    'price_trend_positive': '+3.4% today',
    'procurement_index': 'Procurement Index',
    'procurement_requirements': 'Procurement Requirements',
    'produce_location': 'Produce Location',
    'produce_lot_listed_success': 'Produce lot listed successfully!',
    'produce_specifications': 'Produce Specifications',
    'purchase_sub_1': 'Farmer Location: Meerut\nAgreed Price: ₹2,450/qtl\nTotal Value: ₹2,45,000',
    'purchase_sub_2': 'Farmer Location: Muzaffarnagar\nAgreed Price: ₹2,460/qtl\nTotal Value: ₹3,69,000',
    'purchase_sub_3': 'Farmer Location: Hapur\nAgreed Price: ₹3,050/qtl\nTotal Value: ₹2,44,000',
    'qty_quality_summary': 'Quantity: {qty} • Quality: {quality}',
    'quality_faq': 'Fair Average Quality (FAQ)',
    'quality_grade': 'Quality Grade',
    'quality_grade_a': 'Grade A',
    'quality_grade_b': 'Grade B',
    'quality_grade_standard': 'Quality Grade Standard',
    'quality_standard': 'Standard',
    'quantity_qtl': '{quantity} qtl',
    'rate_unavailable': 'Rate unavailable',
    'rec_requires_live_mandi': 'Recommendation requires live Mandi records for Wheat at Meerut Mandi.',
    'received_offers_heading': 'Received Offers',
    'recent_transactions': 'Recent Transactions',
    'recommended_lots': 'Recommended Lots',
    'refresh_demands': 'Refresh demands',
    'refresh_lots': 'Refresh Lots',
    'refresh_tooltip': 'Refresh',
    'required_by_date': 'Required By Date',
    'required_volume_qtl': 'Required Volume (Quintals)',
    'respond_to_demand_btn': 'Respond to Demand',
    'review_offer_btn': 'Review Offer',
    'review_offer_title': 'Review Offer',
    'review_your_deal_title': 'Review Your Deal',
    'role_buyer': 'Buyer',
    'role_buyer_desc': 'Source directly from farmers, post commodity demands, make bids, and track active purchases.',
    'role_buyer_title': 'I am a Buyer',
    'role_farmer': 'Farmer',
    'role_farmer_desc': 'List produce, track live mandi rates, simulate holding returns, and connect with verified buyers.',
    'role_farmer_title': 'I am a Farmer',
    'route_meerut_karnal': 'Meerut Farm  →  Karnal Mandi (118 km)',
    'run_what_if_simulator': 'Run What-If Price Simulator',
    'scenario_comparison': 'Scenario Comparison',
    'scenario_estimate_trend': 'Scenario estimate based on current market trend',
    'search_produce_location': 'Search produce or mandi location...',
    'select_commodity': 'Select Commodity',
    'select_lot_and_respond': 'Select Lot & Respond',
    'select_lot_title': 'Select Lot',
    'select_mandi': 'Select Mandi',
    'select_required_date_optional': 'Select required-by date (optional)',
    'select_role_title': 'Choose how you want to continue:',
    'select_transport_btn': 'Select Transport',
    'selected_count': '{count} selected',
    'signal_hold': 'HOLD',
    'signal_sell_now': 'SELL NOW',
    'signal_sell_partially': 'SELL PARTIALLY',
    'simulation_requires_rates': 'Simulation requires live mandi rates. Please ensure Wheat rates are recorded in the database.',
    'smart_aggregation': 'Smart Aggregation',
    'smart_aggregation_desc': 'Combine your crop with nearby farmers for larger bulk lots',
    'smart_aggregation_title': 'Smart Aggregation',
    'smart_buyer_matches_title': 'Smart Buyer Matches',
    'status_accepted': 'Accepted',
    'status_active': 'ACTIVE',
    'status_completed': 'Completed',
    'status_confirmed': 'Confirmed',
    'status_delivered': 'Delivered',
    'status_in_transit': 'In Transit',
    'status_label': 'Status',
    'status_payment_pending': 'Payment Pending',
    'status_pending': 'Pending',
    'status_rejected': 'Rejected',
    'step_deal_confirmation': 'Deal Confirmation',
    'step_escrow_deposit': 'Buyer deposits funds into escrow',
    'step_farmer_review': 'Farmer Review',
    'step_logistics_dispatch': 'Logistics arranged for farm pickup',
    'step_offer_submitted': 'Offer Submitted',
    'step_payment_release': 'Payment released immediately upon delivery',
    'target_buying_price': 'Target Buying Price (₹/Quintal)',
    'target_quality_standard': 'Target Quality Standard',
    'test_what_if_return': 'Test What-If / Simulate Return',
    'top_buyer_opportunities': 'Top Buyer Opportunities',
    'total_contract_value': 'Total Contract Value',
    'total_offer_value': 'Total Offer Value',
    'total_value_label': 'Total Value',
    'track_realtime_lots_desc': 'Track real-time lot availability, status, and evaluate market holding returns.',
    'trade_momentum_high': '• High trade momentum',
    'transactions_appear_here_desc': 'When buyer offers are accepted, deal contracts, escrow status, and dispatches will appear here.',
    'transactions_dispatches_title': 'Transactions & Dispatches',
    'transit_route': 'Transit Route',
    'transport_arranged': 'Transport Arranged',
    'transport_arranged_success': 'Transport arranged successfully',
    'transport_details': 'Transport Details',
    'transport_options_title': 'Transport Options',
    'transport_tracking_title': 'Transport Tracking',
    'trend_today_4_2': '+4.2% Today',
    'underlying_market_factors': 'Underlying Market Factors',
    'vehicle_assigned_desc': 'Vehicle assigned and scheduled for pickup.',
    'verify_deal_subtitle': 'Verify deal terms and counterparty details before finalizing',
    'view_all': 'View All',
    'view_buyer_offers': 'View Buyer Offers',
    'view_delivery_details': 'View Delivery Details',
    'view_my_offers_btn': 'View My Offers',
    'volume_with_quality': 'Volume: {volume} • {quality}',
    'what_happens_next': 'What happens next?',
    'what_if_market_simulator': 'What-If Market Simulator',
    'what_if_simulator': 'What-If Simulator',
    'what_if_simulator_desc': 'Test hold duration vs storage charges.',
    'what_if_simulator_title': 'What-If Price Simulator',
    'wheat_demand_200': 'Wheat • Need 200 Quintals',
    'wheat_demand_500': 'Wheat • Need 500 Quintals',
    'when_buyers_broadcast_desc': 'When buyers broadcast requirements matching your harvested crops, compatible procurement opportunities will rank here.',
    'yields_highest_nrv': 'Yields the highest estimated net realisable value for {qty} qtl.',
    'your_matching_lots': 'Your Matching Lots',
    'your_offer_label': 'Your Offer: ',
    // --- Added: intro / auth / voice input ---
    'intro_headline': 'Know the market.\nSell smarter.',
    'intro_sub': 'Live mandi rates, direct buyers and clear SELL / HOLD guidance — in one simple app.',
    'intro_feature_rates': 'Live mandi rates',
    'intro_feature_rates_desc': 'Prices and trends from nearby markets',
    'intro_feature_buyers': 'Direct buyers',
    'intro_feature_buyers_desc': 'Post a lot, receive offers, no middlemen',
    'intro_feature_guidance': 'Sell or hold?',
    'intro_feature_guidance_desc': 'Simple recommendations based on market conditions',
    'intro_get_started': 'Get Started',
    'intro_have_account': 'I already have an account',
    'auth_sign_in_title': 'Sign In',
    'auth_sign_in_sub': 'Welcome back. Enter your details to continue.',
    'auth_create_account_title': 'Create Account',
    'auth_create_account_sub': 'A few details and you are ready to go.',
    'auth_full_name': 'Full Name',
    'auth_full_name_hint': 'e.g., Ramesh Kumar',
    'auth_email': 'Email',
    'auth_email_hint': 'you@example.com',
    'auth_password': 'Password',
    'auth_password_hint': 'At least 6 characters',
    'auth_sign_in_btn': 'Sign In',
    'auth_sign_up_btn': 'Create Account',
    'auth_no_account': 'New here?',
    'auth_sign_up_link': 'Create an account',
    'auth_have_account': 'Already have an account?',
    'auth_sign_in_link': 'Sign in',
    'auth_show_password': 'Show password',
    'auth_hide_password': 'Hide password',
    'auth_sign_out': 'Sign Out',
    'auth_sign_out_confirm': 'Sign out of KisanSetu?',
    'auth_check_email_title': 'Confirm your email',
    'auth_check_email_body': 'We sent a confirmation link to your email. Open it, then sign in.',
    'auth_welcome_back': 'Welcome back,',
    'common_cancel': 'Cancel',
    'common_ok': 'OK',
    'auth_err_name_required': 'Enter your name',
    'auth_err_email_required': 'Enter your email',
    'auth_err_email_invalid': 'Enter a valid email',
    'auth_err_password_required': 'Enter your password',
    'auth_err_password_short': 'Password must be at least 6 characters',
    'auth_err_invalid_credentials': 'Incorrect email or password',
    'auth_err_email_not_confirmed': 'Please confirm your email first, then sign in',
    'auth_err_user_exists': 'An account with this email already exists',
    'auth_err_not_signed_in': 'Please sign in first.',
    'auth_err_generic': 'Something went wrong. Please try again.',
    'voice_tap_to_speak': 'Tap the mic and speak',
    'voice_listening': 'Listening…',
    'voice_translating': 'Translating…',
    'voice_downloading': 'Downloading language pack (one time)…',
    'voice_heard': 'Heard',
    'voice_unavailable': 'Voice input is not available on this device',
    'voice_permission_denied': 'Microphone permission was denied',
    'voice_nothing_heard': 'Nothing heard. Try again.',
    'voice_translate_unavailable': 'Translation works only on Android / iOS. Showing Hindi text.',

    'payment_produce': 'Produce',
    'payment_agreed_price': 'Agreed Price',
    'payment_gross_sale_value': 'Gross Sale Value',
    'payment_transport_cost': 'Transport Cost',
    'payment_method_label': 'Payment Method',
    'payment_method_bank_transfer': 'Direct Bank Transfer',
    'payment_transport_pending': 'Not arranged yet',

    'payment_step_delivery_verified': 'Delivery Verified',
    'payment_step_initiated': 'Payment Initiated',
    'payment_step_received': 'Payment Received',
    'payment_awaiting_delivery': 'Payment starts once the produce is delivered and verified.',

    'not_arranged': 'Not arranged',
    'not_scheduled': 'Not scheduled',
    'not_calculated': 'Not calculated',
    'not_specified': 'Not specified',

  };

  static const Map<String, String> _hiStrings = {
    'accept_offer_btn': 'प्रस्ताव स्वीकार करें',
    'actions_tools': 'कार्य और उपकरण',
    'active_demand_badge': 'सक्रिय मांग',
    'active_demands_badge': '{count} सक्रिय',
    'active_inventory': 'सक्रिय स्टॉक',
    'active_lot_badge': 'सक्रिय लॉट',
    'active_lots_summary': '2 सक्रिय लॉट • 180 क्विंटल',
    'active_market': 'सक्रिय बाज़ार',
    'active_past_purchases': 'सक्रिय और पिछली खरीदारी',
    'aggregation_hero_desc': 'बड़े व्यापार लॉट बनाने, शीर्ष थोक खरीदारों को आकर्षित करने और बेहतर मंडी दरों पर बातचीत करने के लिए पास के सत्यापित किसानों के साथ उपज मिलाएं।',
    'ai_market_signal': 'एआई बाज़ार संकेत',
    'ai_recommendation_wheat': 'आज 40% स्टॉक का लाभ सुरक्षित करें। शेष लॉट अगले सप्ताह संभावित वृद्धि से लाभान्वित हो सकता है।',
    'app_name': 'किसानसेतु',
    'app_tagline': 'प्रत्यक्ष कृषि बाज़ार',
    'asking_price': 'मांगी गई कीमत',
    'asking_price_format': 'मांग: {price}',
    'asking_rate': 'मांगी गई दर',
    'available_from_label': 'उपलब्धता: 03 Sep 2026',
    'available_lots': 'उपलब्ध लॉट',
    'available_quantity': 'उपलब्ध मात्रा',
    'available_vehicles': 'उपलब्ध वाहन',
    'available_volume': 'उपलब्ध मात्रा',
    'available_volume_quintals': 'उपलब्ध मात्रा (क्विंटल)',
    'back_to_dashboard_btn': 'डैशबोर्ड पर वापस जाएं',
    'badge_produce_lot': 'उपज लॉट',
    'badge_ready_to_submit': 'जमा करने के लिए तैयार',
    'based_on_live_trend': 'लाइव मूल्य रुझान ({trend}%) और मांग स्तर ({demand}) के आधार पर।',
    'based_on_price_movement': 'वर्तमान मूल्य के रुझान और खरीदार की मांग के आधार पर',
    'best_fit_badge': 'सर्वोत्तम विकल्प',
    'best_scenario_prefix': 'सर्वश्रेष्ठ परिदृश्य: {scenario}',
    'broadcast_demand_btn': 'मांग प्रसारित करें',
    'broadcast_demand_desc': 'अपनी आवश्यक मात्रा, लक्षित मूल्य और डिलीवरी स्थान प्रसारित करें',
    'browse_farmer_produce_lots': 'किसान उत्पाद लॉट ब्राउज़ करें',
    'browse_lots': 'लॉट ब्राउज़ करें',
    'browse_lots_title': 'लॉट ब्राउज़ करें',
    'browse_lots_to_bid_desc': 'बोली लगाने और किसानों के साथ बातचीत करने के लिए उपलब्ध लॉट ब्राउज़ करें।',
    'bulk_advantage_desc': 'बड़े लॉट थोक खरीदारों को आकर्षित कर सकते हैं और मोलभाव करने की क्षमता बढ़ा सकते हैं।',
    'bulk_selling_advantage': 'थोक बिक्री का लाभ',
    'buyer_demand_board_desc': 'खरीदारों द्वारा पोस्ट की गई सक्रिय कमोडिटी आवश्यकताएं देखें',
    'buyer_demand_board_title': 'खरीदार मांग बोर्ड',
    'buyer_demand_label': 'खरीदार मांग',
    'buyer_demand_overview': 'खरीदार मांग अवलोकन',
    'buyer_offers_title': 'खरीदार के प्रस्ताव',
    'combined_lot_label': 'संयुक्त लॉट',
    'commodity_crop': 'जिंस फसल',
    'common_back': 'वापस',
    'common_retry': 'पुनः प्रयास करें',
    'compare_net_price': 'शुद्ध मूल्य की तुलना करें',
    'compare_sell_hold_desc': 'भंडारण और परिवहन लागत के साथ \'अभी बेचें\' बनाम \'रोक कर रखें\' की तुलना करें।',
    'compatibility_score': 'अनुकूलता स्कोर: {score}%',
    'confirm_and_list_produce': 'पुष्टि करें और उपज लॉट सूचीबद्ध करें',
    'confirm_and_submit_offer': 'पुष्टि करें और प्रस्ताव जमा करें',
    'confirm_deal_btn': 'सौदा पक्का करें',
    'continue_to_make_offer': 'प्रस्ताव देने के लिए आगे बढ़ें',
    'costs_breakdown_text': '• परिवहन: ₹2,500 प्रति ढुलाई\n• भंडारण (7 दिन रोकें): ₹100/क्विंटल\n• भंडारण (15 दिन रोकें): ₹200/क्विंटल',
    'create_aggregated_lot_btn': 'एकत्रित लॉट बनाएं',
    'create_new_lot': 'नया लॉट बनाएं',
    'create_new_lot_desc': 'अपनी फसल सूचीबद्ध करें और खरीदारों से जुड़ें',
    'crop_all': 'सभी',
    'crop_basmati_rice': 'बासमती चावल',
    'crop_chana': 'चना',
    'crop_maize': 'मक्का',
    'crop_market_rate': '{crop} मंडी दर',
    'crop_mustard': 'सरसों',
    'crop_pooling': 'फसल पूलिंग',
    'crop_rice': 'चावल',
    'crop_soybean': 'सोयाबीन',
    'crop_wheat': 'गेहूं',
    'current_market_recommendation': 'वर्तमान मंडी अनुशंसा',
    'data_shown_based_on_records': 'दिखाया गया डेटा KisanSetu में उपलब्ध नवीनतम मंडी रिकॉर्ड पर आधारित है।',
    'deal_number_header': 'सौदा #{number} • {crop} ({qty})',
    'deal_specifications': 'सौदा विनिर्देश',
    'deal_summary': 'सौदा सारांश',
    'decline_offer_btn': 'अस्वीकार करें',
    'delhi_ncr_distance': 'दिल्ली NCR • 65 किमी दूर',
    'delivery_location_depot': 'वितरण स्थान / डिपो',
    'delivery_progress': 'डिलीवरी की प्रगति',
    'delivery_timeline': 'डिलीवरी समयरेखा',
    'direct_bids_realization_desc': 'प्रत्यक्ष संयुक्त बोलियों से वर्तमान में ₹120-150/क्विंटल अधिक प्राप्ति होती है।',
    'direct_farmer_opportunities': 'प्रत्यक्ष किसान अवसर',
    'direct_procurement_savings_desc': 'सीधी खरीद से बिचौलियों के मंडी प्रबंधन और कमीशन शुल्क पर 8% तक की बचत होती है।',
    'direct_purchase_reqs_desc': 'संस्थागत खरीदारों द्वारा पोस्ट की गई सीधी खरीद आवश्यकताएं यहां दिखाई देंगी।',
    'dispatch_route': 'प्रेषण मार्ग',
    'dispatch_status_updated': 'प्रेषण स्थिति {status} में अपडेट की गई',
    'dispatches_deals_desc': 'स्वीकृत सौदे, पिकअप और सीधे भुगतान ट्रैक करें',
    'dispatches_deals_title': 'डिस्पैच और सौदे',
    'distance_away': '{distance} किमी दूर',
    'enter_quantity_in_qtl': 'क्विंटल में मात्रा दर्ज करें',
    'err_cannot_exceed_qty': 'उपलब्ध लॉट मात्रा ({qty}) से अधिक नहीं हो सकता',
    'err_enter_asking_rate': 'मांगी गई दर दर्ज करें',
    'err_enter_delivery_location': 'वितरण स्थान दर्ज करें',
    'err_enter_qty': 'मात्रा दर्ज करें',
    'err_enter_target_price': 'लक्षित मूल्य दर्ज करें',
    'err_enter_warehouse_loc': 'फार्म/गोदाम का स्थान दर्ज करें',
    'err_incomplete_offer_details': 'अपूर्ण प्रस्ताव विवरण। स्वीकृति के साथ आगे नहीं बढ़ सकते।',
    'err_invalid_price_or_qty': 'अमान्य प्रस्ताव मूल्य या मात्रा।',
    'err_must_be_gt_0': '0 से अधिक होना चाहिए',
    'err_offer_not_found': 'प्रस्ताव विवरण नहीं मिल सका।',
    'err_offer_price_req': 'प्रस्तावित मूल्य आवश्यक है',
    'err_qty_req': 'मात्रा आवश्यक है',
    'err_valid_price': '0 से अधिक मान्य मूल्य दर्ज करें',
    'err_valid_qty': '0 से अधिक मान्य मात्रा दर्ज करें',
    'escrow_details': 'एस्क्रो विवरण',
    'estimated_contract_total': 'अनुमानित कुल अनुबंध मूल्य',
    'estimated_net_realisable_price': 'अनुमानित शुद्ध वसूली मूल्य',
    'estimated_prototype_costs': 'अनुमानित लागत विवरण',
    'estimated_total_value': 'अनुमानित कुल मूल्य',
    'expected_within_24h': 'डिलीवरी सत्यापन के 24 घंटे के भीतर अपेक्षित',
    'failed_accept_offer': 'प्रस्ताव स्वीकार करने में विफल: {error}',
    'failed_create_lot': 'लॉट बनाने में विफल: {error}',
    'failed_decline_offer': 'प्रस्ताव अस्वीकार करने में विफल। कृपया पुनः प्रयास करें।',
    'failed_load_active_lots': 'सक्रिय लॉट लोड करने में विफल। कृपया पुनः प्रयास करें।',
    'failed_load_offers': 'आपके प्रस्ताव लोड करने में विफल। कृपया पुनः प्रयास करें।',
    'failed_update_status': 'स्थिति अपडेट करने में विफल: {error}',
    'farm_warehouse_depot': 'फार्म गोदाम / ग्रामीण डिपो',
    'farmer_asking_price': 'किसान की मांगी गई कीमत',
    'farmer_asking_rate': 'किसान की मांगी गई दर (₹/क्विंटल)',
    'final_payable_amount': 'अंतिम देय राशि',
    'fulfillment_timeline': 'पूर्ति समयरेखा',
    'good_quality': 'अच्छी गुणवत्ता',
    'greeting_afternoon': 'शुभ दोपहर,',
    'greeting_evening': 'शुभ संध्या,',
    'greeting_morning': 'सुप्रभात,',
    'harvest_lot_volume_qtl': 'काटी गई फसल की मात्रा (क्विंटल)',
    'harvested_lot_details': 'काटी गई उपज का विवरण',
    'harvested_produce_lots': 'काटी गई उपज के लॉट',
    'hint_delivery_location': 'उदा. मेरठ डिपो, परतापुर',
    'hint_farm_warehouse': 'उदा. फार्म गोदाम, दौराला',
    'intelligent_matching': 'इंटेलिजेंट खरीदार मिलान',
    'intelligent_matching_desc': 'संस्थागत खरीदारों के बीच शुद्ध प्राप्य दरों की तुलना करें',
    'intelligent_matching_title': 'इंटेलिजेंट खरीदार मिलान',
    'lang_en': 'English',
    'lang_hi': 'हिन्दी',
    'language': 'भाषा',
    'list_produce_lot_title': 'उपज लॉट सूचीबद्ध करें',
    'listed_lots_count': '{count} सूचीबद्ध लॉट',
    'listings_count': '{count} सूचियाँ',
    'live_apmc': 'लाइव APMC',
    'live_data_badge': 'लाइव डेटा',
    'logistics_fulfillment_title': 'लॉजिस्टिक्स और पूर्ति',
    'logistics_label': 'लॉजिस्टिक्स',
    'logistics_tracking_desc': 'प्रस्ताव स्वीकार होने के बाद लॉजिस्टिक्स ट्रैकिंग और प्रेषण व्यवस्था दिखाई देगी।',
    'lot_details_title': 'लॉट विवरण',
    'lot_distance': 'दूरी',
    'lot_id_format': 'लॉट आईडी: {id}',
    'lot_id_label': 'लॉट आईडी',
    'lot_id_prefix': 'लॉट आईडी: {id}',
    'lot_location': 'स्थान',
    'lot_quality': 'गुणवत्ता',
    'lot_quantity': 'मात्रा',
    'make_an_offer': 'प्रस्ताव दें',
    'make_offer_title': 'प्रस्ताव दें',
    'make_offer_view_lot': 'प्रस्ताव दें / लॉट देखें',
    'manage_produce_batches': 'उपज बैच प्रबंधित करें',
    'mandi_comparison': 'मंडी तुलना',
    'mandi_location_label': 'मंडी / स्थान',
    'mandi_rate_meerut': 'मेरठ मंडी दर',
    'market_advisory_title': 'मंडी सलाह',
    'market_assumptions': 'मंडी मान्यताएं',
    'market_intelligence_title': 'मंडी भाव व विश्लेषण',
    'market_overview': 'बाज़ार अवलोकन',
    'market_recommendation': 'बाज़ार अनुशंसा',
    'market_recommendation_desc': 'लाइव मंडी स्थितियों के आधार पर रोकें / बेचें मार्गदर्शन प्राप्त करें',
    'market_recommendation_title': 'बाज़ार अनुशंसा',
    'max_available_helper': 'अधिकतम उपलब्ध: {qty}',
    'model_net_returns_desc': 'भंडारण और भाड़ा कटौती के साथ \'अभी बेचें\' बनाम \'रोक कर रखें\' के शुद्ध लाभ का मॉडल।',
    'msg_aggregated_lot_success': 'एकत्रित लॉट सफलतापूर्वक बनाया गया',
    'msg_demand_broadcasted': 'खरीद मांग सफलतापूर्वक प्रसारित की गई!',
    'msg_failed_post_demand': 'मांग पोस्ट करने में विफल: {error}',
    'my_active_lots_desc': 'सूचीबद्ध फसलें, सक्रिय लॉट देखें और प्रस्ताव प्रबंधित करें',
    'my_active_lots_title': 'मेरे सक्रिय लॉट',
    'my_lots': 'मेरे लॉट',
    'my_lots_desc': 'अपनी सूचीबद्ध फसलों को देखें और प्रबंधित करें',
    'my_offers': 'मेरे प्रस्ताव',
    'my_produce_lots_title': 'मेरे उपज लॉट',
    'my_purchases': 'मेरी खरीदारियां',
    'my_purchases_title': 'मेरी खरीदारी',
    'my_submitted_offers': 'मेरे प्रस्तुत प्रस्ताव',
    'my_submitted_offers_desc': 'लंबित बोलियां, स्वीकृत सौदे और किसान के जवाबी प्रस्ताव ट्रैक करें',
    'my_submitted_offers_title': 'मेरे प्रस्तुत प्रस्ताव',
    'nearby_farmers': 'पास के किसान',
    'need_active_lot_desc': 'इस खरीदार की मांग का जवाब देने के लिए आपको उपलब्ध मात्रा के साथ {crop} के एक सक्रिय लॉट की आवश्यकता है।',
    'net_price': 'शुद्ध मूल्य',
    'net_rate_2490': '₹2,490/क्विंटल शुद्ध',
    'net_rate_2520': '₹2,520/क्विंटल शुद्ध',
    'net_realisable_breakdown': 'शुद्ध प्राप्य मूल्य विवरण',
    'net_realisable_value': 'शुद्ध वसूली मूल्य',
    'no_active_buyer_demands': 'कोई सक्रिय खरीदार मांग नहीं',
    'no_active_buyer_demands_found': 'कोई सक्रिय खरीदार मांग नहीं मिली।',
    'no_active_farmer_lots': 'वर्तमान में कोई सक्रिय किसान लॉट सूचीबद्ध नहीं है।',
    'no_active_lots': 'कोई सक्रिय लॉट उपलब्ध नहीं है',
    'no_buyer_offers_yet': 'अभी तक कोई खरीदार प्रस्ताव प्राप्त नहीं हुआ',
    'no_confirmed_deals': 'कोई पुष्ट सौदा नहीं मिला',
    'no_data_available_crop_market': '{market} में {crop} के लिए वर्तमान में कोई डेटा उपलब्ध नहीं है।',
    'no_market_data_wheat': 'गेहूं के लिए कोई मंडी डेटा नहीं मिला',
    'no_matching_active_lots': 'कोई मेल खाने वाला सक्रिय लॉट नहीं मिला',
    'no_offers_submitted_yet': 'अभी तक कोई प्रस्ताव प्रस्तुत नहीं किया गया',
    'no_produce_lots_found': 'कोई उपज लॉट नहीं मिला',
    'no_recorded_rates_found': 'कोई दर्ज दर नहीं मिली',
    'no_transactions_found': 'कोई लेन-देन नहीं मिला',
    'noida_hub_distance': 'नोएडा हब • 48 किमी दूर',
    'notif_buyer_offer_desc': 'किसान एग्रो फ्लोर मिल्स ने आपके गेहूं लॉट के लिए ₹2,470/क्विंटल की पेशकश की।\n10 मिनट पहले',
    'notif_buyer_offer_title': 'नया खरीदार प्रस्ताव',
    'notif_logistics_desc': 'आपके गेहूं शिपमेंट के लिए परिवहन की व्यवस्था कर दी गई है।\nकल',
    'notif_logistics_title': 'लॉजिस्टिक्स अपडेट',
    'notif_market_alert_desc': 'मेरठ में आज गेहूं की कीमतों में 3.4% की वृद्धि हुई।\n1 घंटा पहले',
    'notif_market_alert_title': 'बाज़ार अलर्ट',
    'notif_offer_update_desc': 'गेहूं 150 क्विंटल के लिए आपका प्रस्ताव स्वीकार कर लिया गया।\n3 घंटे पहले',
    'notif_offer_update_title': 'प्रस्ताव अपडेट',
    'notifications_title': 'सूचनाएं',
    'offer_accepted_success': 'प्रस्ताव सफलतापूर्वक स्वीकार कर लिया गया! सौदा अनुबंध बनाया गया।',
    'offer_declined_msg': 'प्रस्ताव अस्वीकार कर दिया गया',
    'offer_details_title': 'प्रस्ताव विवरण',
    'offer_progress': 'प्रस्ताव की प्रगति',
    'offer_submitted_desc': 'आपकी बोली सीधे किसान तक पहुंचा दी गई है। उनके उत्तर देने पर आपको सूचित किया जाएगा।',
    'offer_submitted_title': 'प्रस्ताव प्रस्तुत हुआ!',
    'offer_summary': 'प्रस्ताव सारांश',
    'offer_terms': 'प्रस्ताव की शर्तें',
    'offered_price_label': 'प्रस्तावित मूल्य (₹/क्विंटल)',
    'offered_quantity_label': 'प्रस्तावित मात्रा (क्विंटल)',
    'offered_unit_price': 'प्रस्तावित इकाई मूल्य',
    'offered_volume': 'प्रस्तावित मात्रा',
    'offers_appear_here_desc': 'संभावित खरीदारों द्वारा प्रस्तुत प्रस्ताव यहां दिखाई देंगे।',
    'offers_count_badge': '{count} प्रस्ताव',
    'orders_count': '{count} ऑर्डर',
    'payment_auto_update_desc': 'खरीदार द्वारा बैंक निपटान पूरा करने के बाद भुगतान की स्थिति अपने आप अपडेट हो जाएगी। राशि सीधे आपके पंजीकृत बैंक खाते में जमा कर दी जाएगी।',
    'payment_breakdown': 'भुगतान विवरण',
    'payment_details_title': 'भुगतान विवरण',
    'payment_timeline': 'भुगतान समयरेखा',
    'per_quintal_benchmark_wheat': '/ क्विंटल बेंचमार्क (गेहूं)',
    'per_quintal_wheat': '/ क्विंटल (गेहूं)',
    'post_commodity_demand_title': 'कमोडिटी मांग पोस्ट करें',
    'post_crops_broadcast_desc': 'उपलब्ध मात्रा प्रसारित करने और खरीदार के प्रस्ताव प्राप्त करने के लिए अपनी काटी गई फसलें पोस्ट करें।',
    'post_demand': 'मांग पोस्ट करें',
    'post_demand_title': 'जिंस मांग पोस्ट करें',
    'post_new_lot_btn': 'नया लॉट जोड़ें',
    'post_new_produce_lot_desc': 'गुणवत्ता, मात्रा और मांग मूल्य के साथ कटी हुई फसल सूचीबद्ध करें',
    'post_new_produce_lot_title': 'नया उत्पाद लॉट पोस्ट करें',
    'post_produce_lot_btn': 'उपज लॉट पोस्ट करें',
    'premium_quality': 'प्रीमियम गुणवत्ता',
    'price_per_qtl': '₹{price}/क्विंटल',
    'price_realisation_simulator': 'मूल्य वसूली सिम्युलेटर',
    'price_trend_positive': '+3.4% आज',
    'procurement_index': 'खरीद सूचकांक',
    'procurement_requirements': 'खरीद आवश्यकताएं',
    'produce_location': 'उपज का स्थान',
    'produce_lot_listed_success': 'उपज लॉट सफलतापूर्वक सूचीबद्ध किया गया!',
    'produce_specifications': 'उपज विनिर्देश',
    'purchase_sub_1': 'किसान का स्थान: मेरठ\nसहमति मूल्य: ₹2,450/क्विंटल\nकुल मूल्य: ₹2,45,000',
    'purchase_sub_2': 'किसान का स्थान: मुज़फ्फरनगर\nसहमति मूल्य: ₹2,460/क्विंटल\nकुल मूल्य: ₹3,69,000',
    'purchase_sub_3': 'किसान का स्थान: हापुड़\nसहमति मूल्य: ₹3,050/क्विंटल\nकुल मूल्य: ₹2,44,000',
    'qty_quality_summary': 'मात्रा: {qty} • गुणवत्ता: {quality}',
    'quality_faq': 'उचित औसत गुणवत्ता (FAQ)',
    'quality_grade': 'गुणवत्ता ग्रेड',
    'quality_grade_a': 'ग्रेड A',
    'quality_grade_b': 'ग्रेड B',
    'quality_grade_standard': 'गुणवत्ता ग्रेड मानक',
    'quality_standard': 'मानक',
    'quantity_qtl': '{quantity} क्विंटल',
    'rate_unavailable': 'दर उपलब्ध नहीं है',
    'rec_requires_live_mandi': 'सलाह के लिए मेरठ मंडी में गेहूं के लाइव रिकॉर्ड की आवश्यकता है।',
    'received_offers_heading': 'प्राप्त प्रस्ताव',
    'recent_transactions': 'हाल के लेन-देन',
    'recommended_lots': 'अनुशंसित लॉट',
    'refresh_demands': 'मांगों को रीफ्रेश करें',
    'refresh_lots': 'लॉट रीफ्रेश करें',
    'refresh_tooltip': 'रीफ्रेश करें',
    'required_by_date': 'किस तारीख तक आवश्यक',
    'required_volume_qtl': 'आवश्यक मात्रा (क्विंटल)',
    'respond_to_demand_btn': 'मांग का जवाब दें',
    'review_offer_btn': 'प्रस्ताव की समीक्षा करें',
    'review_offer_title': 'प्रस्ताव की समीक्षा करें',
    'review_your_deal_title': 'अपने सौदे की समीक्षा करें',
    'role_buyer': 'खरीदार',
    'role_buyer_desc': 'सीधे किसानों से खरीदें, कमोडिटी मांग पोस्ट करें, बोलियां लगाएं और सक्रिय खरीदारी ट्रैक करें।',
    'role_buyer_title': 'मैं एक खरीदार हूँ',
    'role_farmer': 'किसान',
    'role_farmer_desc': 'उत्पाद सूचीबद्ध करें, लाइव मंडी दरें ट्रैक करें, होल्डिंग रिटर्न सिम्युलेट करें और सत्यापित खरीदारों से जुड़ें।',
    'role_farmer_title': 'मैं एक किसान हूँ',
    'route_meerut_karnal': 'मेरठ फार्म  →  करनाल मंडी (118 किमी)',
    'run_what_if_simulator': 'मूल्य सिम्युलेटर चलाएं',
    'scenario_comparison': 'परिदृश्य तुलना',
    'scenario_estimate_trend': 'वर्तमान बाजार रुझान पर आधारित परिदृश्य अनुमान',
    'search_produce_location': 'उपज या मंडी स्थान खोजें...',
    'select_commodity': 'जिंस चुनें',
    'select_lot_and_respond': 'लॉट चुनें और जवाब दें',
    'select_lot_title': 'लॉट चुनें',
    'select_mandi': 'मंडी चुनें',
    'select_required_date_optional': 'आवश्यक तारीख चुनें (वैकल्पिक)',
    'select_role_title': 'चुनें कि आप कैसे जारी रखना चाहते हैं:',
    'select_transport_btn': 'परिवहन चुनें',
    'selected_count': '{count} चयनित',
    'signal_hold': 'रोक कर रखें',
    'signal_sell_now': 'अभी बेचें',
    'signal_sell_partially': 'आंशिक बिक्री करें',
    'simulation_requires_rates': 'सिम्युलेटर के लिए लाइव मंडी दरों की आवश्यकता है। कृपया सुनिश्चित करें कि डेटाबेस में गेहूं की दरें दर्ज हैं।',
    'smart_aggregation': 'स्मार्ट एकत्रीकरण',
    'smart_aggregation_desc': 'बड़े थोक लॉट के लिए पास के किसानों के साथ अपनी फसल मिलाएं',
    'smart_aggregation_title': 'स्मार्ट एकत्रीकरण',
    'smart_buyer_matches_title': 'स्मार्ट खरीदार मिलान',
    'status_accepted': 'स्वीकृत',
    'status_active': 'सक्रिय',
    'status_completed': 'पूर्ण',
    'status_confirmed': 'पुष्टि की गई',
    'status_delivered': 'वितरित',
    'status_in_transit': 'पारगमन में',
    'status_label': 'स्थिति',
    'status_payment_pending': 'भुगतान लंबित',
    'status_pending': 'लंबित',
    'status_rejected': 'अस्वीकृत',
    'step_deal_confirmation': 'सौदा पुष्टि',
    'step_escrow_deposit': 'खरीदार एस्क्रो में धनराशि जमा करता है',
    'step_farmer_review': 'किसान समीक्षा',
    'step_logistics_dispatch': 'खेत से उठाने के लिए लॉजिस्टिक्स की व्यवस्था',
    'step_offer_submitted': 'प्रस्ताव प्रस्तुत',
    'step_payment_release': 'डिलीवरी के तुरंत बाद भुगतान जारी',
    'target_buying_price': 'लक्षित खरीद मूल्य (₹/क्विंटल)',
    'target_quality_standard': 'लक्षित गुणवत्ता मानक',
    'test_what_if_return': 'अनुमान लगाएं / लाभ सिम्युलेट करें',
    'top_buyer_opportunities': 'शीर्ष खरीदार अवसर',
    'total_contract_value': 'कुल अनुबंध मूल्य',
    'total_offer_value': 'कुल प्रस्ताव मूल्य',
    'total_value_label': 'कुल मूल्य',
    'track_realtime_lots_desc': 'वास्तविक समय में लॉट की उपलब्धता, स्थिति ट्रैक करें और बाजार में रोक कर रखने के लाभ का आकलन करें।',
    'trade_momentum_high': '• उच्च व्यापार गति',
    'transactions_appear_here_desc': 'जब खरीदार के प्रस्ताव स्वीकार किए जाएंगे, तो सौदा अनुबंध, एस्क्रो स्थिति और प्रेषण यहां दिखाई देंगे।',
    'transactions_dispatches_title': 'लेन-देन और प्रेषण',
    'transit_route': 'पारगमन मार्ग',
    'transport_arranged': 'परिवहन व्यवस्थित',
    'transport_arranged_success': 'परिवहन की व्यवस्था सफलतापूर्वक हो गई',
    'transport_details': 'परिवहन विवरण',
    'transport_options_title': 'परिवहन विकल्प',
    'transport_tracking_title': 'परिवहन ट्रैकिंग',
    'trend_today_4_2': '+4.2% आज',
    'underlying_market_factors': 'अंतर्निहित मंडी कारक',
    'vehicle_assigned_desc': 'वाहन आवंटित किया गया और पिकअप के लिए निर्धारित किया गया।',
    'verify_deal_subtitle': 'अंतिम रूप देने से पहले सौदे की शर्तों और खरीदार के विवरण की पुष्टि करें',
    'view_all': 'सभी देखें',
    'view_buyer_offers': 'खरीदार के प्रस्ताव देखें',
    'view_delivery_details': 'डिलीवरी विवरण देखें',
    'view_my_offers_btn': 'मेरे प्रस्ताव देखें',
    'volume_with_quality': 'मात्रा: {volume} • {quality}',
    'what_happens_next': 'आगे क्या होगा?',
    'what_if_market_simulator': 'मंडी मूल्य सिम्युलेटर',
    'what_if_simulator': 'व्हाट-इफ सिम्युलेटर',
    'what_if_simulator_desc': 'होल्ड अवधि बनाम भंडारण शुल्क का परीक्षण करें।',
    'what_if_simulator_title': 'मूल्य सिम्युलेटर',
    'wheat_demand_200': 'गेहूं • 200 क्विंटल आवश्यक',
    'wheat_demand_500': 'गेहूं • 500 क्विंटल आवश्यक',
    'when_buyers_broadcast_desc': 'जब खरीदार आपकी फसल से मेल खाने वाली आवश्यकताएं प्रसारित करेंगे, तो अनुकूल खरीद अवसर यहां क्रमबद्ध होंगे।',
    'yields_highest_nrv': '{qty} क्विंटल के लिए उच्चतम अनुमानित शुद्ध वसूली मूल्य प्राप्त होता है।',
    'your_matching_lots': 'आपके मेल खाने वाले लॉट',
    'your_offer_label': 'आपका प्रस्ताव: ',
    // --- Added: intro / auth / voice input ---
    'intro_headline': 'बाज़ार जानिए।\nसमझदारी से बेचिए।',
    'intro_sub': 'लाइव मंडी भाव, सीधे खरीदार और साफ़ बेचें / रोकें सलाह — एक आसान ऐप में।',
    'intro_feature_rates': 'लाइव मंडी भाव',
    'intro_feature_rates_desc': 'आस-पास की मंडियों के भाव और रुझान',
    'intro_feature_buyers': 'सीधे खरीदार',
    'intro_feature_buyers_desc': 'लॉट डालें, ऑफ़र पाएँ, बिना बिचौलिये',
    'intro_feature_guidance': 'बेचें या रोकें?',
    'intro_feature_guidance_desc': 'बाज़ार की स्थिति पर आधारित आसान सलाह',
    'intro_get_started': 'शुरू करें',
    'intro_have_account': 'मेरा खाता पहले से है',
    'auth_sign_in_title': 'साइन इन',
    'auth_sign_in_sub': 'वापसी पर स्वागत है। जारी रखने के लिए विवरण भरें।',
    'auth_create_account_title': 'खाता बनाएँ',
    'auth_create_account_sub': 'कुछ विवरण और आप तैयार हैं।',
    'auth_full_name': 'पूरा नाम',
    'auth_full_name_hint': 'जैसे, रमेश कुमार',
    'auth_email': 'ईमेल',
    'auth_email_hint': 'aap@example.com',
    'auth_password': 'पासवर्ड',
    'auth_password_hint': 'कम से कम 6 अक्षर',
    'auth_sign_in_btn': 'साइन इन करें',
    'auth_sign_up_btn': 'खाता बनाएँ',
    'auth_no_account': 'नए हैं?',
    'auth_sign_up_link': 'खाता बनाएँ',
    'auth_have_account': 'खाता पहले से है?',
    'auth_sign_in_link': 'साइन इन',
    'auth_show_password': 'पासवर्ड दिखाएँ',
    'auth_hide_password': 'पासवर्ड छिपाएँ',
    'auth_sign_out': 'साइन आउट',
    'auth_sign_out_confirm': 'किसानसेतु से साइन आउट करें?',
    'auth_check_email_title': 'अपना ईमेल पुष्टि करें',
    'auth_check_email_body': 'हमने आपके ईमेल पर पुष्टि लिंक भेजा है। उसे खोलें, फिर साइन इन करें।',
    'auth_welcome_back': 'वापसी पर स्वागत है,',
    'common_cancel': 'रद्द करें',
    'common_ok': 'ठीक है',
    'auth_err_name_required': 'अपना नाम लिखें',
    'auth_err_email_required': 'अपना ईमेल लिखें',
    'auth_err_email_invalid': 'सही ईमेल लिखें',
    'auth_err_password_required': 'अपना पासवर्ड लिखें',
    'auth_err_password_short': 'पासवर्ड कम से कम 6 अक्षर का हो',
    'auth_err_invalid_credentials': 'ईमेल या पासवर्ड गलत है',
    'auth_err_email_not_confirmed': 'पहले अपना ईमेल पुष्टि करें, फिर साइन इन करें',
    'auth_err_user_exists': 'इस ईमेल से खाता पहले से है',
    'auth_err_not_signed_in': 'कृपया पहले साइन इन करें।',
    'auth_err_generic': 'कुछ गड़बड़ हुई। फिर से कोशिश करें।',
    'voice_tap_to_speak': 'माइक दबाएँ और बोलें',
    'voice_listening': 'सुन रहे हैं…',
    'voice_translating': 'अनुवाद हो रहा है…',
    'voice_downloading': 'भाषा पैक डाउनलोड हो रहा है (एक बार)…',
    'voice_heard': 'सुना',
    'voice_unavailable': 'इस डिवाइस पर आवाज़ इनपुट उपलब्ध नहीं है',
    'voice_permission_denied': 'माइक्रोफ़ोन की अनुमति नहीं मिली',
    'voice_nothing_heard': 'कुछ सुनाई नहीं दिया। फिर से कोशिश करें।',
    'voice_translate_unavailable': 'अनुवाद केवल Android / iOS पर काम करता है। हिंदी पाठ दिखाया जा रहा है।',

    'payment_produce': 'उपज',
    'payment_agreed_price': 'सहमति मूल्य',
    'payment_gross_sale_value': 'कुल बिक्री मूल्य',
    'payment_transport_cost': 'परिवहन लागत',
    'payment_method_label': 'भुगतान का तरीका',
    'payment_method_bank_transfer': 'सीधा बैंक ट्रांसफ़र',
    'payment_transport_pending': 'अभी तय नहीं',

    'payment_step_delivery_verified': 'डिलीवरी सत्यापित',
    'payment_step_initiated': 'भुगतान शुरू',
    'payment_step_received': 'भुगतान प्राप्त',
    'payment_awaiting_delivery': 'उपज पहुँचने और सत्यापित होने के बाद भुगतान शुरू होता है।',

    'not_arranged': 'तय नहीं',
    'not_scheduled': 'निर्धारित नहीं',
    'not_calculated': 'गणना नहीं हुई',
    'not_specified': 'नहीं बताया गया',

  };

  void _loadBuiltInStrings() {
    if (locale.languageCode == 'hi') {
      _localizedStrings = Map.from(_hiStrings);
    } else {
      _localizedStrings = Map.from(_enStrings);
    }
  }

  /// Loads strings from asset JSON files if available, merging them into memory.
  ///
  /// Not called by the delegate any more (see [_AppLocalizationsDelegate.load]).
  /// Kept for the case where translations should be shipped as data instead of
  /// being compiled in; call it before showing the UI if you re-enable it.
  Future<bool> loadJsonAsset() async {
    try {
      final jsonString = await rootBundle
          .loadString('assets/lang/${locale.languageCode}.json');
      final Map<String, dynamic> jsonMap = json.decode(jsonString);
      jsonMap.forEach((key, value) {
        _localizedStrings[key] = value.toString();
      });
      return true;
    } catch (_) {
      // Gracefully uses built-in strings if asset file is missing or in tests
      return false;
    }
  }

  /// Translates a given [key] into the active language.
  /// Any dynamic [args] replaced in `{param}` and the output text are
  /// strictly guaranteed to have English digits (0-9) via [NumberFormatter.ensureEnglishDigits].
  String translate(String key, {Map<String, dynamic>? args}) {
    var text = _localizedStrings[key] ?? _enStrings[key] ?? key;

    if (args != null && args.isNotEmpty) {
      args.forEach((argKey, argValue) {
        final val = NumberFormatter.ensureEnglishDigits(argValue.toString());
        text = text.replaceAll('{$argKey}', val);
      });
    }

    // Strict number formatting exception rule:
    // When language is Hindi, all numbers remain in English digits (0-9).
    return NumberFormatter.ensureEnglishDigits(text);
  }

  /// Convenient alias for [translate].
  String tr(String key, {Map<String, dynamic>? args}) =>
      translate(key, args: args);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLanguage.values
        .map((lang) => lang.code)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    // Synchronous on purpose. The built-in dictionaries above already hold
    // every key (assets/lang/*.json is kept in sync as a copy), so there is
    // nothing to await. An async load makes Localizations render an empty
    // frame while the future resolves — the screen flashes blank on every
    // language switch, and in widget tests nothing renders at all because
    // asset I/O does not complete inside the test's fake-async zone.
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
